remote_theme: pages-themes/midnight@v0.2.0
repository: OpenKneeboard/OpenKneeboard
title: OpenKneeboard
description: Interactive information in your simulators
show_downloads: true
plugins:
- jekyll-remote-theme
