name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0
      - name: Fetch code-signing key
        env:
          CODE_SIGNING_PFX_BASE64: ${{ secrets.CODE_SIGNING_KEY_PFX_BASE64 }}
        id: FetchKey
        if: ${{ (matrix.config != 'Debug') && (github.repository == 'OpenKneeboard/OpenKneeboard') && (github.event_name == 'push')}}
        shell: pwsh
        run: |
          [System.Convert]::FromBase64String($Env:CODE_SIGNING_PFX_BASE64) | Set-Content ${{runner.temp}}/MyCert.pfx -AsByteStream
          Add-Content $Env:GITHUB_OUTPUT "HAVE_KEY=true"
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        id: configure
        run: |
          $args = @(
            "-DGITHUB_REF_TYPE=${{github.ref_type}}",
            "-DGITHUB_REF_NAME=${{github.ref_name}}"
          )
          if (Test-Path -Path "${{runner.temp}}/MyCert.pfx") {
            $args += "-DSIGNTOOL_KEY_ARGS=/f;${{runner.temp}}/MyCert.pfx" `
          }
          cmake ${{github.workspace}}/source @args
          $version ="$(Get-Content version.txt)"
          Add-Content $Env:GITHUB_OUTPUT "VERSION=${version}"
      - name: Compile
        working-directory: build
        run: |
          cmake --build . `
            --config ${{matrix.config}} `
            --parallel `
            -- `
            /p:CL_MPCount=
      - name: Create MSI
        working-directory: build
        id: createMSI
        run: |
          echo "::group::Running CPack"
          cmake --build . `
            --config ${{matrix.config}} `
            --target package
          $installer="OpenKneeboard-$(Get-Content version.txt).msi"
          Add-Content $Env:GITHUB_OUTPUT "MSI_NAME=$installer"
          $installer=(Get-ChildItem $installer).FullName
          Add-Content $Env:GITHUB_OUTPUT "MSI_PATH=$installer"
          echo "::endgroup::"
          if (Test-Path -Path "${{runner.temp}}\MyCert.pfx") {
            echo "::group::Signing MSI"
            # Known path for the GitHub Actions windows 2022 runner, may need updating
            & 'C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\signtool.exe' `
              sign `
              /t http://timestamp.digicert.com `
              /fd SHA256 `
              /f "${{runner.temp}}/MyCert.pfx" `
              $installer
            echo "::endgroup::"
          }
      - name: Attach MSI
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: OpenKneeboard-GHA-${{github.run_number}}.msi
          path:
            ${{steps.createMSI.outputs.MSI_PATH}}
      - name: Install debug symbols
        id: installDebugSymbols
        working-directory: build
        shell: pwsh
        run:
          $prefix="${{runner.temp}}/OpenKneeboard-${{steps.configure.outputs.VERSION}}-Symbols"
          cmake --install . `
            --config ${{matrix.config}} `
            --component DebugSymbols `
            --prefix "${prefix}"

          Add-Content $Env:GITHUB_OUTPUT "PREFIX=$prefix"
      - name: Attach debug symbols
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: OpenKneeboard-GHA-${{github.run_number}}-Symbols
          path:
          path: ${{steps.installDebugSymbols.outputs.PREFIX}}
    strategy:
      matrix:
        config: [RelWithDebInfo, Debug]
  release:
    name: Prepare Draft Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
      - name: Generate release notes
        run: sed 's/@TAG@/${{github.ref_name}}/g' source/.github/workflows/release_notes.md > ${{runner.temp}}/release_notes.md
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{runner.temp}}/artifacts
      - name: Display downloaded files
        run: ls -R
        working-directory: ${{runner.temp}}/artifacts
      - name: Create zip files
        run: |
          ZIP_ARTIFACT="-Symbols"
          cd ${{runner.temp}}/artifacts/OpenKneeboard-GHA-${{github.run_number}}${ZIP_ARTIFACT}
          zip -r \
            "${{runner.temp}}/OpenKneeboard-${{github.ref_name}}${ZIP_ARTIFACT}.zip" \
            ./

          cd ${{runner.temp}}/artifacts/OpenKneeboard-GHA-${{github.run_number}}.msi
          mv *.msi OpenKneeboard-${{github.ref_name}}.msi
      - name: Create draft release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          draft: true
          body_path: ${{runner.temp}}/release_notes.md
      - name: Attach MSI
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{runner.temp}}/OpenKneeboard-${{github.ref_name}}.msi
          asset_name: OpenKneeboard-${{github.ref_name}}.msix
          asset_content_type: application/msix
      - name: Attach -RelWithDebInfo-Symbols.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{runner.temp}}/OpenKneeboard-${{github.ref_name}}-Symbols.zip
          asset_name: OpenKneeboard-${{github.ref_name}}-Symbols.zip
          asset_content_type: application/zip
