name: Build and Package
on:
  pull_request:
    paths:
      - "assets/**"
      - "installer/**"
      - "src/**"
      - "third-party/**"
      - "*.props"
      - "*.cmake"
      - "CMakeLists.txt"
      - ".github/workflows/ci.yml"
  push:
    paths:
      - "assets/**"
      - "installer/**"
      - "src/**"
      - "third-party/**"
      - "*.props"
      - "*.cmake"
      - "CMakeLists.txt"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    strategy:
      matrix:
        config: [RelWithDebInfo, Debug]
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
          fetch-depth: 0
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          $args = @(
            "-A", "x64"
          )
          cmake ${{github.workspace}}/source @args
      - name: Build
        id: build
        working-directory: build
        run: |
          # Build
          echo "::group::Running cmake --build"
          cmake --build . `
            --config ${{matrix.config}} `
            --parallel `
            -- `
            /p:CL_MPCount=
          echo "::endgroup::"
          echo "::group::Setting version"
          $version="$(Get-Content version.txt)"
          Add-Content $Env:GITHUB_OUTPUT "VERSION=${version}"
          echo "::endgroup::"
      - name: Attach debug symbols
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v4
        with:
          name: OpenKneeboard-GHA${{github.run_number}}-Symbols
          path: build/out/${{matrix.config}}/pdb
      - name: Build installer generator
        if: ${{matrix.config != 'Debug' }}
        shell: pwsh
        working-directory: source/OpenKneeboard-Installer
        run: |
          dotnet publish `
            --configuration Release `
            --output "build/out/${{matrix.config}}/installer-generator"
      - name: Attach bundle
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v4
        with:
          name: OpenKneeboard-GHA${{github.run_number}}
          path: |
            build/out/${{matrix.config}}
            !build/out/${{matrix.config}}/pdb
      - name: Generate release notes
        if: github.ref_type == 'tag' && matrix.config != 'Debug'
        id: release-notes
        run: |
          $out = "${{runner.temp}}/release_notes.md"
            (Get-Content -Path source/.github/workflows/release_notes.md -raw) `
            -replace '@TAG@','${{github.ref_name}}' | `
            Set-Content -Path $out -Encoding UTF8
          Add-Content $Env:GITHUB_OUTPUT "PATH=$out"
      - name: Create draft release
        id: create-release
        if: github.ref_type == 'tag' && matrix.config != 'Debug'
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          draft: true
          body_path: ${{steps.release-notes.outputs.PATH}}
          prerelease: ${{contains(github.ref_name, '-')}}