name: Publish to OpenKneeboard/autoupdates repository
on:
  push:
    branches:
      - master
    paths:
      - autoupdate/**
  workflow_dispatch:
jobs:
  publish:
    if: github.repository == 'OpenKneeboard/OpenKneeboard'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0
      - name: Push
        working-directory: source
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git subtree push --prefix=autoupdate "https://${{secrets.OPENKNEEBOARD_BOT_PAT}}@github.com/OpenKneeboard/autoupdates.git" main
