name: Sync gh-pages branch
on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - .github/workflows/pages-sync.yml
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Push to gh-pages branch"
        run: git subtree push --prefix docs/ origin gh-pages
